name: Bedwars
verze     : 4.1.0
api     : 3.2.0
hlavní            : Bluplayz \ BedWars
autor    : NetherTechnology
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
